micronaut:
  application:
    name: buses

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/Buses`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:123456}
    driver-class-name: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'com.bus.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true